baseURL = 'https://ctf.adamino.dk/'
languageCode = 'en-us'
title = 'Adamino CTF Writeups'
theme = 'hermit-v2'
ignoreFiles = ["README.md", "README"]
ignoreLogs = ['warning-goldmark-raw-html']

defaultContentLanguage = "en"

[mediaTypes]
  [mediaTypes."text/html"]
    suffixes = ["html"]

[outputFormats]
  [outputFormats.HTML]
    mediaType = "text/html"
    path = ""
    
[outputs]
  home = ["HTML"]
  section = ["HTML"] 
  page = ["HTML"]
copyright = "Adamino 2023"
# googleAnalytics = "UA-123-451"

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  dateform        = "2 Jan, 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "02-01-2006"
  dateformNumTime = "15:04 02-01-2006 -0700"

  bgImg = "aCTF.webp"

  scrollToTop = true
  footerCopyright = "The quieter you become the more you are able to hear"


[params.author]
  name = "Adamino"
  about = ""


[languages]
  [languages.en]
    title = 'Adamino CTF Writeups'
    [languages.en.params]
      homeSubtitle = "Awesome CTF Writeups"
  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/onero"

[menu]

  [[menu.main]]
    name = "Tools"
    url = "tools/"
    weight = 2

  [[menu.main]]
    name = "NC3"
    url = "nc3/"
    weight = 10